export const authEndpoints = Object.freeze({
  login: "/api/v1/auth/login/",
  logout: "/api/v1/auth/logout/",
  refresh: "/api/v1/auth/token/refresh/",
  me: "/api/v1/auth/me/",
  register: "/api/v1/auth/register/",
  switchAccount: (id: string) => `/api/v1/auth/switch/${id}/`,
  switchRole: "/api/v1/auth/switch-role/",
  children: "/api/v1/auth/children/",
  links: "/api/v1/auth/links/",
  requestLink: "/api/v1/auth/links/request/",
  respondLink: (id: string) => `/api/v1/auth/links/${id}/respond/`,
  consents: "/api/v1/auth/consents/",
  logins: "/api/v1/auth/logins/",
  teachers: "/api/v1/auth/teachers/",
  teachersPending: "/api/v1/auth/teachers/pending/",
  myRatings: "/api/v1/auth/me/ratings/",
  teacherRatings: (id: string) => `/api/v1/auth/teachers/${id}/ratings/`,
  teacherStats: (id: string) => `/api/v1/auth/teachers/${id}/stats/`,
  teacherApprove: (id: string) => `/api/v1/auth/teachers/${id}/approve/`,
  meCertificates: "/api/v1/auth/me/certificates/",
  meCertificate: (id: string) => `/api/v1/auth/me/certificates/${id}/`,
});
